# backend/alembic/script.py.mako
"""Add Scenario model

Revision ID: 2ad21707424c
Revises: s1e2e3d4t5p6
Create Date: 2026-01-18 06:03:10.852417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ad21707424c'
down_revision: Union[str, None] = 's1e2e3d4t5p6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scenarios',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('event_count', sa.Integer(), nullable=False),
    sa.Column('required_roles', sa.JSON(), nullable=False),
    sa.Column('events', sa.JSON(), nullable=False),
    sa.Column('is_seed', sa.Boolean(), nullable=False),
    sa.Column('seed_id', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('seed_id')
    )
    op.create_index(op.f('ix_scenarios_name'), 'scenarios', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scenarios_name'), table_name='scenarios')
    op.drop_table('scenarios')
    # ### end Alembic commands ###
