# backend/alembic/script.py.mako
"""Remove isolation_level from networks

Revision ID: 2eea4468d2ce
Revises: a9393b918352
Create Date: 2026-01-16 02:02:49.045160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2eea4468d2ce'
down_revision: Union[str, None] = 'a9393b918352'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('networks', 'isolation_level')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('networks', sa.Column('isolation_level', postgresql.ENUM('COMPLETE', 'CONTROLLED', 'OPEN', name='isolationlevel'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
