# backend/alembic/script.py.mako
"""add_network_id_to_event_logs

Revision ID: 33972ed2512c
Revises: 51af2acf294b
Create Date: 2026-01-18 03:31:52.479448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33972ed2512c'
down_revision: Union[str, None] = '51af2acf294b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_logs', sa.Column('network_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_event_logs_network_id'), 'event_logs', ['network_id'], unique=False)
    op.create_foreign_key(None, 'event_logs', 'networks', ['network_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'event_logs', type_='foreignkey')
    op.drop_index(op.f('ix_event_logs_network_id'), table_name='event_logs')
    op.drop_column('event_logs', 'network_id')
    # ### end Alembic commands ###
