# backend/alembic/script.py.mako
"""enhance snapshot model for vm library

Revision ID: 3e5c6dd8470c
Revises: d3e4f5g6h7i8
Create Date: 2026-01-19 22:57:44.986729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e5c6dd8470c'
down_revision: Union[str, None] = 'd3e4f5g6h7i8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('range_blueprints', 'is_seed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))

    # Add new columns for VM Library feature
    op.add_column('snapshots', sa.Column('docker_image_tag', sa.String(length=255), nullable=True))
    op.add_column('snapshots', sa.Column('os_type', sa.String(length=20), nullable=True))
    op.add_column('snapshots', sa.Column('vm_type', sa.String(length=20), nullable=True))
    op.add_column('snapshots', sa.Column('display_type', sa.String(length=20), nullable=True))

    # Add columns with server defaults for existing rows
    op.add_column('snapshots', sa.Column('default_cpu', sa.Integer(), nullable=False, server_default='2'))
    op.add_column('snapshots', sa.Column('default_ram_mb', sa.Integer(), nullable=False, server_default='4096'))
    op.add_column('snapshots', sa.Column('default_disk_gb', sa.Integer(), nullable=False, server_default='40'))
    op.add_column('snapshots', sa.Column('vnc_port', sa.Integer(), nullable=False, server_default='8006'))
    op.add_column('snapshots', sa.Column('is_global', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('snapshots', sa.Column('tags', sa.JSON(), nullable=False, server_default='[]'))

    # Make vm_id optional (snapshots can exist independently as imported images)
    op.alter_column('snapshots', 'vm_id',
               existing_type=sa.UUID(),
               nullable=True)

    # Add index on name for faster lookups
    op.create_index(op.f('ix_snapshots_name'), 'snapshots', ['name'], unique=False)

    # Change foreign key from CASCADE to SET NULL (keep snapshot when VM is deleted)
    op.drop_constraint('snapshots_vm_id_fkey', 'snapshots', type_='foreignkey')
    op.create_foreign_key(None, 'snapshots', 'vms', ['vm_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'snapshots', type_='foreignkey')
    op.create_foreign_key('snapshots_vm_id_fkey', 'snapshots', 'vms', ['vm_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_snapshots_name'), table_name='snapshots')
    op.alter_column('snapshots', 'vm_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('snapshots', 'tags')
    op.drop_column('snapshots', 'is_global')
    op.drop_column('snapshots', 'vnc_port')
    op.drop_column('snapshots', 'display_type')
    op.drop_column('snapshots', 'default_disk_gb')
    op.drop_column('snapshots', 'default_ram_mb')
    op.drop_column('snapshots', 'default_cpu')
    op.drop_column('snapshots', 'vm_type')
    op.drop_column('snapshots', 'os_type')
    op.drop_column('snapshots', 'docker_image_tag')
    op.alter_column('range_blueprints', 'is_seed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###
