# backend/alembic/script.py.mako
"""add_range_blueprints

Revision ID: 51af2acf294b
Revises: a62a84db3bfa
Create Date: 2026-01-18 01:42:36.966273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51af2acf294b'
down_revision: Union[str, None] = 'a62a84db3bfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('range_blueprints',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('base_subnet_prefix', sa.String(length=20), nullable=False),
    sa.Column('next_offset', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_range_blueprints_name'), 'range_blueprints', ['name'], unique=False)
    op.create_table('range_instances',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('blueprint_id', sa.Uuid(), nullable=False),
    sa.Column('blueprint_version', sa.Integer(), nullable=False),
    sa.Column('subnet_offset', sa.Integer(), nullable=False),
    sa.Column('instructor_id', sa.Uuid(), nullable=False),
    sa.Column('range_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['blueprint_id'], ['range_blueprints.id'], ),
    sa.ForeignKeyConstraint(['instructor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['range_id'], ['ranges.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('range_instances')
    op.drop_index(op.f('ix_range_blueprints_name'), table_name='range_blueprints')
    op.drop_table('range_blueprints')
    # ### end Alembic commands ###
