# backend/alembic/script.py.mako
"""add_walkthrough_progress_table

Revision ID: a62a84db3bfa
Revises: ca6cb7955d32
Create Date: 2026-01-17 23:16:11.393484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a62a84db3bfa'
down_revision: Union[str, None] = 'ca6cb7955d32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('walkthrough_progress',
    sa.Column('range_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('completed_steps', sa.JSON(), nullable=False),
    sa.Column('current_phase', sa.String(length=100), nullable=True),
    sa.Column('current_step', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['range_id'], ['ranges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('range_id', 'user_id', name='uq_walkthrough_progress_range_user')
    )
    op.create_index(op.f('ix_walkthrough_progress_range_id'), 'walkthrough_progress', ['range_id'], unique=False)
    op.create_index(op.f('ix_walkthrough_progress_user_id'), 'walkthrough_progress', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_walkthrough_progress_user_id'), table_name='walkthrough_progress')
    op.drop_index(op.f('ix_walkthrough_progress_range_id'), table_name='walkthrough_progress')
    op.drop_table('walkthrough_progress')
    # ### end Alembic commands ###
