# backend/alembic/script.py.mako
"""Add is_isolated field to networks

Revision ID: a9393b918352
Revises: h2i3j4k5l6m7
Create Date: 2026-01-16 01:32:28.814535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9393b918352'
down_revision: Union[str, None] = 'h2i3j4k5l6m7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add is_isolated with default value for existing rows
    op.add_column('networks', sa.Column('is_isolated', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.alter_column('vms', 'linux_user_sudo',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vms', 'linux_user_sudo',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_column('networks', 'is_isolated')
    # ### end Alembic commands ###
