# backend/alembic/script.py.mako
"""add os_family and os_version to templates

Revision ID: c7c4ced81dd3
Revises: e57dfc82c9fc
Create Date: 2026-01-18 20:39:31.740432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7c4ced81dd3'
down_revision: Union[str, None] = 'e57dfc82c9fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vm_templates', sa.Column('os_family', sa.String(length=50), nullable=True))
    op.add_column('vm_templates', sa.Column('os_version', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_vm_templates_os_family'), 'vm_templates', ['os_family'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vm_templates_os_family'), table_name='vm_templates')
    op.drop_column('vm_templates', 'os_version')
    op.drop_column('vm_templates', 'os_family')
    # ### end Alembic commands ###
