# backend/alembic/script.py.mako
"""add_walkthrough_to_msel

Revision ID: ca6cb7955d32
Revises: 9d3a537d0321
Create Date: 2026-01-17 23:14:19.993014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca6cb7955d32'
down_revision: Union[str, None] = '9d3a537d0321'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('msels', sa.Column('walkthrough', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('msels', 'walkthrough')
    # ### end Alembic commands ###
