# backend/alembic/script.py.mako
"""add lifecycle timestamps and user to events

Revision ID: fd5d01a50586
Revises: 33972ed2512c
Create Date: 2026-01-18 04:07:36.187524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd5d01a50586'
down_revision: Union[str, None] = '33972ed2512c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_logs', sa.Column('user_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_event_logs_user_id'), 'event_logs', ['user_id'], unique=False)
    op.create_foreign_key(None, 'event_logs', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.add_column('ranges', sa.Column('deployed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('ranges', sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('ranges', sa.Column('stopped_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ranges', 'stopped_at')
    op.drop_column('ranges', 'started_at')
    op.drop_column('ranges', 'deployed_at')
    op.drop_constraint(None, 'event_logs', type_='foreignkey')
    op.drop_index(op.f('ix_event_logs_user_id'), table_name='event_logs')
    op.drop_column('event_logs', 'user_id')
    # ### end Alembic commands ###
